import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";

export default function Home(props) {
  console.log(props);

  useEffect(() => {
    localStorage.setItem('asdf', 'asdf'); // 1/10
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav
        style={{
          border: "1px solid red",
          display: "flex",
          gap: "10px",
          height: "10vh",
          justifyContent: "space-around",
          alignItems: "center",
        }}
      >
        <h1>Logo</h1>
        <Link href={"/about"}>About</Link>
      </nav>
      <div
        style={{
          display: "grid",
          gap: "10px",
          gridTemplateColumns: "repeat(4, 1fr)",
        }}
      >
        {props.res.map((ele, ind) => (
          <div style={{ border: "1px solid white", padding: "10px" }} key={ind}>
            <h1>{ele.first_name}</h1>
            <Image src={ele.avatar} width={50} height={50} />
          </div>
        ))}
      </div>

      <Image
        src={
          "https://images.unsplash.com/photo-1575239005176-a1e644188f51?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
        }
        width={100}
        height={100}
      />
    </>
  );
}

export async function getStaticProps(context) {
  let data = await fetch("http://localhost:3000/api/employees");
  let res = await data.json();

  return {
    props: {
      res: res.employees,
    },
  };
}
